# Generated by Django 2.1.5 on 2019-01-21 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(db_index=True, max_length=150, verbose_name='Название блога')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='О чем этот блог')),
                ('date_recreate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_recreate'],
            },
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name='Комментарий')),
                ('date_publ', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('date_republ', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('settings', models.BooleanField(default=True, verbose_name='Возможность комментария')),
                ('author_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['date_republ'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('preview', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Тизер')),
                ('text_post', models.TextField(blank=True, db_index=True, verbose_name='Текст пост ')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('sum_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('attr_to_view', models.BooleanField(choices=[(True, 'Виден всем'), (False, 'Виден мне')], verbose_name='Настройки видимости поста')),
                ('sum_comments', models.IntegerField(default=0, verbose_name='Все комментарии')),
                ('setting_comments', models.BooleanField(default=True, verbose_name='Возможность комментария')),
                ('send_comment', models.CharField(max_length=50, verbose_name='Комментировать')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.BlogAuthor', verbose_name='Автор')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Blog')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adres', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('date_visit', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время просмотра')),
                ('entry_page', models.TextField(verbose_name='Страница входа')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.BlogAuthor', verbose_name='Пользователь')),
                ('view_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Post', verbose_name='Просматриваемый пост')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Post'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog_page.BlogAuthor', verbose_name='Автор'),
        ),
    ]
