# Generated by Django 2.1.5 on 2019-01-27 18:07

import blog_page.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', blog_page.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(db_index=True, max_length=150, verbose_name='Название блога')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='О чем этот блог')),
                ('date_recreate', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-date_recreate'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name='Комментарий')),
                ('date_publ', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('date_republ', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('settings', models.BooleanField(default=True, verbose_name='Возможность комментария')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('author_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['date_republ'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('preview', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Тизер')),
                ('text_post', markdownx.models.MarkdownxField(blank=True, db_index=True, verbose_name='Текст поста')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('sum_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('attr_to_view', models.BooleanField(choices=[(True, 'Виден всем'), (False, 'Виден мне')], verbose_name='Настройки видимости поста')),
                ('sum_comments', models.IntegerField(default=0, verbose_name='Все комментарии')),
                ('setting_comments', models.BooleanField(default=True, verbose_name='Возможность комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Blog')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adres', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('date_visit', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время просмотра')),
                ('entry_page', models.TextField(verbose_name='Страница входа')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('view_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Post', verbose_name='Просматриваемый пост')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Post'),
        ),
    ]
