# Generated by Django 2.1.5 on 2019-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='setting_comments',
            field=models.BooleanField(choices=[(True, 'Комментировать'), (False, 'Не комментировать')], default=True, verbose_name='Возможность комментария'),
        ),
    ]
