# Generated by Django 2.1.5 on 2019-01-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='post',
            name='send_comment',
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, verbose_name='Текст поста'),
        ),
    ]
