# Generated by Django 2.1.5 on 2019-01-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0002_auto_20190124_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_page.BlogAuthor', verbose_name='Пользователь'),
        ),
    ]
