# Generated by Django 2.1.5 on 2019-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='entry_page',
            field=models.TextField(blank=True, null=True, verbose_name='Страница входа'),
        ),
    ]
